[package]
name = "api-proxy-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
hyper-util = "0.1.10"
reqwest = { version = "0.12.12", features = ["json", "rustls-tls"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
